services:

  web:
    environment:
      TZ: Europe/Moscow

    build:
      args:
        - build_env=production
      context: .
      target: production

#    volumes:
#      - type: bind
#        source: ./supervisord.log
#        target: /project/supervisord.log
