services:

  web:

    build:
      context: .
      target: development

    ports:
      - '5030:8000'

    volumes:
      - type: bind
        source: ./application
        target: /project/application
