services:

  web:

    build:
      args:
        - build_env=production
      context: .
      target: production

    volumes:
      - 'aiohttp:/tmp/aiohttp'
      - 'static:/project/application/static'

volumes:
  aiohttp:
  static:
