name: Test_container

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:

  Test_container:

    runs-on: ubuntu-latest
    container: python
      volumes:
        /next-project:/next-project

    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install pipenv
        mkdir .venv
        pipenv install --dev --skip-lock

    - name: Lint with flake8
      run: |
        pipenv run flake8 application --count --select=E9,F63,F7,F82 --show-source --statistics
        pipenv run flake8 application --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: pipenv run pytest --cov

    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v1.3.2
